(() => {
  "use strict";

  const SUBJECT_DEFS = Object.freeze([
    {
      id: "english",
      subject: "英语岛",
      label: "英语",
      title: "英语小耳朵",
      description: "听一个短词，用图片找到它。",
      icon: "🎈",
      duration: "3 分钟",
      color: "#4f8fdf",
      soft: "#e8f2ff",
    },
    {
      id: "chinese",
      subject: "语文岛",
      label: "语文",
      title: "汉字小花园",
      description: "从熟悉的图画里认识简单汉字。",
      icon: "🪁",
      duration: "4 分钟",
      color: "#ec6c73",
      soft: "#ffedf0",
    },
    {
      id: "math",
      subject: "数学岛",
      label: "数学",
      title: "数字小火车",
      description: "数一数、比一比，再找找规律。",
      icon: "🐞",
      duration: "3 分钟",
      color: "#db9f20",
      soft: "#fff6cf",
    },
    {
      id: "science",
      subject: "科学岛",
      label: "科学",
      title: "自然发现站",
      description: "观察身边的小现象，大胆猜一猜。",
      icon: "🌱",
      duration: "4 分钟",
      color: "#59aa75",
      soft: "#e9f8ee",
    },
    {
      id: "music",
      subject: "音乐岛",
      label: "音乐",
      title: "节奏小乐队",
      description: "拍拍手、找节奏，让身体听见音乐。",
      icon: "🎵",
      duration: "3 分钟",
      color: "#a56cc1",
      soft: "#f4ebfa",
    },
    {
      id: "movement",
      subject: "活力岛",
      label: "运动",
      title: "身体加油站",
      description: "轻轻跳一跳，练习平衡和协调。",
      icon: "🐸",
      duration: "2 分钟",
      color: "#32a6a2",
      soft: "#e4f7f5",
    },
    {
      id: "life",
      subject: "生活岛",
      label: "综合 / 生活",
      title: "生活小能手",
      description: "练习照顾自己，也友好地对待别人。",
      icon: "🏡",
      duration: "3 分钟",
      color: "#e48645",
      soft: "#fff0df",
    },
  ].map((subject) => Object.freeze(subject)));

  const subjectById = SUBJECT_DEFS.reduce((result, subject) => {
    result[subject.id] = subject;
    return result;
  }, {});

  function makeLesson(subjectId, details) {
    const subject = subjectById[subjectId];
    const lesson = {
      ...subject,
      ...details,
      subjectId,
    };

    if (lesson.options) {
      lesson.options = Object.freeze(
        lesson.options.map((option) => Object.freeze({ ...option })),
      );
    }

    if (lesson.pattern) lesson.pattern = Object.freeze([...lesson.pattern]);
    return Object.freeze(lesson);
  }

  const DAILY_LESSON_BANK = Object.freeze({
    english: Object.freeze([
      makeLesson("english", {
        id: "english-red-apple",
        title: "红苹果在哪里",
        description: "听一听 red，再找到红色的苹果。",
        type: "listen",
        instruction: "点喇叭听一听，再选出 red。",
        word: "red",
        speech: "Red. Red apple. Can you find the red apple?",
        options: [
          { label: "红苹果", emoji: "🍎", value: "red" },
          { label: "黄香蕉", emoji: "🍌", value: "yellow" },
          { label: "青葡萄", emoji: "🍇", value: "green" },
        ],
        answer: "red",
        hint: "Red 是红色。看看红红的小苹果。",
      }),
      makeLesson("english", {
        id: "english-blue-balloon",
        title: "蓝气球飞呀飞",
        description: "听懂 blue，找出蓝色气球。",
        type: "listen",
        instruction: "先听 blue，再点一点正确的气球。",
        word: "blue",
        speech: "Blue. Blue balloon. Can you find the blue balloon?",
        options: [
          { label: "蓝气球", emoji: "🔵", value: "blue" },
          { label: "红气球", emoji: "🔴", value: "red" },
          { label: "黄气球", emoji: "🟡", value: "yellow" },
        ],
        answer: "blue",
        hint: "Blue 是蓝色。不着急，再听一次也可以。",
      }),
      makeLesson("english", {
        id: "english-cat-friend",
        title: "谁是 Cat",
        description: "听动物名字，找到可爱的小猫。",
        type: "listen",
        instruction: "点喇叭听 cat，再选出小猫。",
        word: "cat",
        speech: "Cat. A little cat. Can you find the cat?",
        options: [
          { label: "小猫", emoji: "🐱", value: "cat" },
          { label: "小狗", emoji: "🐶", value: "dog" },
          { label: "小兔", emoji: "🐰", value: "rabbit" },
        ],
        answer: "cat",
        hint: "Cat 是小猫，轻轻说一遍：cat。",
      }),
      makeLesson("english", {
        id: "english-hello-wave",
        title: "Hello，你好呀",
        description: "听见 hello，找出挥手问好的动作。",
        type: "listen",
        instruction: "听一听，哪一个动作是在说 hello？",
        word: "hello",
        speech: "Hello! Hello, my friend! Wave your hand and say hello!",
        options: [
          { label: "挥挥手", emoji: "👋", value: "hello" },
          { label: "睡觉觉", emoji: "😴", value: "sleep" },
          { label: "吃水果", emoji: "🍐", value: "eat" },
        ],
        answer: "hello",
        hint: "Hello 是“你好”。可以一边挥手一边说。",
      }),
      makeLesson("english", {
        id: "english-jump-command",
        title: "听口令 Jump",
        description: "听懂一个动作词，再做一做。",
        type: "listen",
        instruction: "点喇叭听口令，选出 jump 的动作。",
        word: "jump",
        speech: "Jump! Jump, jump! Can you find the jumping action?",
        options: [
          { label: "跳一跳", emoji: "⬆️", value: "jump" },
          { label: "坐一坐", emoji: "🪑", value: "sit" },
          { label: "拍拍手", emoji: "👏", value: "clap" },
        ],
        answer: "jump",
        hint: "Jump 是“跳一跳”。试着轻轻跳一下吧。",
      }),
    ]),

    chinese: Object.freeze([
      makeLesson("chinese", {
        id: "chinese-sun-character",
        title: "太阳变成“日”",
        description: "看着太阳，认识汉字“日”。",
        type: "choice",
        instruction: "太阳亮亮的，哪个字是“日”？",
        options: [
          { label: "日", emoji: "☀️", value: "日" },
          { label: "山", emoji: "⛰️", value: "山" },
          { label: "水", emoji: "💧", value: "水" },
        ],
        answer: "日",
        hint: "太阳也叫“日”。先看看带太阳的选项。",
      }),
      makeLesson("chinese", {
        id: "chinese-tree-character",
        title: "小树变成“木”",
        description: "从树干和树枝认识汉字“木”。",
        type: "choice",
        instruction: "一棵小树站得直直的，哪个字是“木”？",
        options: [
          { label: "火", emoji: "🔥", value: "火" },
          { label: "木", emoji: "🌳", value: "木" },
          { label: "口", emoji: "👄", value: "口" },
        ],
        answer: "木",
        hint: "“木”像一棵伸开树枝的小树。再试试看。",
      }),
      makeLesson("chinese", {
        id: "chinese-mouth-character",
        title: "方方的小嘴巴",
        description: "观察嘴巴的形状，认识汉字“口”。",
        type: "choice",
        instruction: "张开小嘴说“啊”，哪个字是“口”？",
        options: [
          { label: "口", emoji: "👄", value: "口" },
          { label: "月", emoji: "🌙", value: "月" },
          { label: "人", emoji: "🧍", value: "人" },
        ],
        answer: "口",
        hint: "“口”方方的，像画出来的小嘴巴。",
      }),
      makeLesson("chinese", {
        id: "chinese-find-same-moon",
        title: "“月”字找朋友",
        description: "在三个字里找到一模一样的“月”。",
        type: "choice",
        instruction: "看一看“月”，下面哪个字和它一样？",
        options: [
          { label: "日", emoji: "☀️", value: "日" },
          { label: "目", emoji: "👀", value: "目" },
          { label: "月", emoji: "🌙", value: "月" },
        ],
        answer: "月",
        hint: "从上到下慢慢看，找一个完全一样的字。",
      }),
      makeLesson("chinese", {
        id: "chinese-animal-sound",
        title: "小动物怎么叫",
        description: "把熟悉的小动物和声音连起来。",
        type: "choice",
        instruction: "小猫见到你，会发出什么声音？",
        options: [
          { label: "喵喵", emoji: "🐱", value: "meow" },
          { label: "汪汪", emoji: "🐶", value: "woof" },
          { label: "嘎嘎", emoji: "🦆", value: "quack" },
        ],
        answer: "meow",
        hint: "想一想小猫撒娇时的声音，再试一次。",
      }),
    ]),

    math: Object.freeze([
      makeLesson("math", {
        id: "math-count-three-apples",
        title: "三颗小苹果",
        description: "指着苹果，一个一个数。",
        type: "count",
        instruction: "一共有几颗苹果？慢慢数一数。",
        count: 3,
        countEmoji: "🍎",
        options: [
          { label: "2", value: "2" },
          { label: "3", value: "3" },
          { label: "4", value: "4" },
        ],
        answer: "3",
        hint: "用小手指着数：1、2、3。",
      }),
      makeLesson("math", {
        id: "math-count-five-ducks",
        title: "小鸭排排队",
        description: "小鸭排好队，等你来数一数。",
        type: "count",
        instruction: "从左到右数，小鸭一共有几只？",
        count: 5,
        countEmoji: "🐥",
        options: [
          { label: "4", value: "4" },
          { label: "5", value: "5" },
          { label: "6", value: "6" },
        ],
        answer: "5",
        hint: "每只只数一次：1、2、3、4、5。",
      }),
      makeLesson("math", {
        id: "math-big-small",
        title: "大象和小蚂蚁",
        description: "观察大小，找到更大的动物。",
        type: "choice",
        instruction: "大象和蚂蚁比，谁更大？",
        options: [
          { label: "大象", emoji: "🐘", value: "elephant" },
          { label: "蚂蚁", emoji: "🐜", value: "ant" },
          { label: "一样大", emoji: "↔️", value: "same" },
        ],
        answer: "elephant",
        hint: "想一想，谁需要更大的房子呢？大胆试试。",
      }),
      makeLesson("math", {
        id: "math-shape-pattern",
        title: "形状接龙",
        description: "圆形和三角形轮流出现。",
        type: "pattern",
        instruction: "圆、三角、圆、三角……接下来是什么？",
        pattern: ["🔵", "🔺", "🔵", "🔺"],
        options: [
          { label: "圆形", emoji: "🔵", value: "circle" },
          { label: "正方形", emoji: "🟩", value: "square" },
          { label: "星星", emoji: "⭐", value: "star" },
        ],
        answer: "circle",
        hint: "它们在轮流出现：圆、三角、圆、三角……",
      }),
      makeLesson("math", {
        id: "math-count-two-cars",
        title: "两辆小汽车",
        description: "认识数量 2，练习一一对应。",
        type: "count",
        instruction: "停车场里有几辆小汽车？",
        count: 2,
        countEmoji: "🚙",
        options: [
          { label: "1", value: "1" },
          { label: "2", value: "2" },
          { label: "3", value: "3" },
        ],
        answer: "2",
        hint: "一辆、两辆。数完就可以选答案啦。",
      }),
    ]),

    science: Object.freeze([
      makeLesson("science", {
        id: "science-seed-grows",
        title: "谁会发芽",
        description: "发现一颗种子怎样慢慢长大。",
        type: "choice",
        instruction: "放进泥土、浇一点水，谁可能会发芽？",
        options: [
          { label: "种子", emoji: "🫘", value: "seed" },
          { label: "石头", emoji: "🪨", value: "stone" },
          { label: "积木", emoji: "🧱", value: "block" },
        ],
        answer: "seed",
        hint: "小小的种子里面，藏着一棵植物。",
      }),
      makeLesson("science", {
        id: "science-fish-home",
        title: "小鱼的家",
        description: "想一想小鱼平时住在哪里。",
        type: "choice",
        instruction: "小鱼最喜欢生活在哪里？",
        options: [
          { label: "水里", emoji: "🌊", value: "water" },
          { label: "树上", emoji: "🌳", value: "tree" },
          { label: "云朵里", emoji: "☁️", value: "cloud" },
        ],
        answer: "water",
        hint: "小鱼用鳃在水里呼吸。你一定能找到。",
      }),
      makeLesson("science", {
        id: "science-rainy-day",
        title: "下雨啦",
        description: "观察天气，选择合适的小物品。",
        type: "choice",
        instruction: "外面正在下雨，带上什么可以挡雨？",
        options: [
          { label: "雨伞", emoji: "☂️", value: "umbrella" },
          { label: "枕头", emoji: "🛏️", value: "pillow" },
          { label: "积木", emoji: "🧱", value: "block" },
        ],
        answer: "umbrella",
        hint: "雨伞打开后，像一顶小屋顶。",
      }),
      makeLesson("science", {
        id: "science-ice-melts",
        title: "冰块变变变",
        description: "知道冰块遇到温暖会慢慢融化。",
        type: "choice",
        instruction: "冰块放在温暖的房间里，会慢慢变成什么？",
        options: [
          { label: "水", emoji: "💧", value: "water" },
          { label: "沙子", emoji: "🏖️", value: "sand" },
          { label: "叶子", emoji: "🍃", value: "leaf" },
        ],
        answer: "water",
        hint: "冰块融化后湿湿的。猜一猜，再试试看。",
      }),
      makeLesson("science", {
        id: "science-plant-drink",
        title: "小花喝什么",
        description: "学习用水照顾一棵小植物。",
        type: "choice",
        instruction: "泥土有点干，小花需要喝什么？",
        options: [
          { label: "清水", emoji: "🚿", value: "water" },
          { label: "彩笔", emoji: "🖍️", value: "crayon" },
          { label: "小石头", emoji: "🪨", value: "stone" },
        ],
        answer: "water",
        hint: "植物和我们一样，也需要水。少量浇水就好。",
      }),
    ]),

    music: Object.freeze([
      makeLesson("music", {
        id: "music-clap-stomp-pattern",
        title: "拍拍手，跺跺脚",
        description: "看懂两个动作轮流出现的节奏。",
        type: "pattern",
        instruction: "拍手、跺脚、拍手、跺脚……接下来做什么？",
        pattern: ["👏", "👣", "👏", "👣"],
        options: [
          { label: "拍拍手", emoji: "👏", value: "clap" },
          { label: "摇摇头", emoji: "🙂", value: "shake" },
          { label: "睡一觉", emoji: "😴", value: "sleep" },
        ],
        answer: "clap",
        hint: "跟着做一遍：拍、跺、拍、跺……",
      }),
      makeLesson("music", {
        id: "music-drum-instrument",
        title: "咚咚小鼓",
        description: "认识一种可以敲响的乐器。",
        type: "choice",
        instruction: "哪一个是敲一敲会“咚咚”响的小鼓？",
        options: [
          { label: "小鼓", emoji: "🥁", value: "drum" },
          { label: "雨伞", emoji: "☂️", value: "umbrella" },
          { label: "小袜子", emoji: "🧦", value: "sock" },
        ],
        answer: "drum",
        hint: "用两根鼓槌轻轻敲，会听见咚咚声。",
      }),
      makeLesson("music", {
        id: "music-note-pattern",
        title: "音符颜色队",
        description: "用颜色观察简单的音乐规律。",
        type: "pattern",
        instruction: "蓝音符、黄音符轮流来，接下来是谁？",
        pattern: ["🎵🔵", "🎵🟡", "🎵🔵", "🎵🟡"],
        options: [
          { label: "蓝音符", emoji: "🔵", value: "blue-note" },
          { label: "红音符", emoji: "🔴", value: "red-note" },
          { label: "绿音符", emoji: "🟢", value: "green-note" },
        ],
        answer: "blue-note",
        hint: "蓝、黄、蓝、黄，它们在轮流排队。",
      }),
      makeLesson("music", {
        id: "music-count-bells",
        title: "三声小铃铛",
        description: "数数铃铛，给节奏配上数量。",
        type: "count",
        instruction: "叮、叮、叮！这里有几个小铃铛？",
        count: 3,
        countEmoji: "🔔",
        options: [
          { label: "2", value: "2" },
          { label: "3", value: "3" },
          { label: "4", value: "4" },
        ],
        answer: "3",
        hint: "指着铃铛数：1、2、3。",
      }),
      makeLesson("music", {
        id: "music-rhythm-jumps",
        title: "四拍跳跳舞",
        description: "跟着四拍节奏轻轻跳。",
        type: "movement",
        instruction: "听心里的拍子：1、2、3、4，轻轻跳 4 下。",
        target: 4,
        hint: "身边留出空位，慢慢跳也很好。每次跳完点一下。",
      }),
    ]),

    movement: Object.freeze([
      makeLesson("movement", {
        id: "movement-frog-three",
        title: "青蛙轻轻跳",
        description: "弯弯膝盖，练习三次轻柔落地。",
        type: "movement",
        instruction: "像小青蛙一样轻轻跳 3 下。",
        target: 3,
        hint: "先看看旁边有没有东西，脚掌轻轻落地。",
      }),
      makeLesson("movement", {
        id: "movement-frog-four",
        title: "跳过四片叶子",
        description: "想象叶子排成队，向上跳一跳。",
        type: "movement",
        instruction: "每跳一下就越过一片叶子，一共跳 4 下。",
        target: 4,
        hint: "不用跳得高，稳稳落地就很棒。",
      }),
      makeLesson("movement", {
        id: "movement-frog-five",
        title: "五颗星星能量",
        description: "用五次小跳唤醒身体。",
        type: "movement",
        instruction: "轻轻跳 5 下，每一下点亮一颗星。",
        target: 5,
        hint: "可以请大人在旁边陪着，慢慢完成。",
      }),
      makeLesson("movement", {
        id: "movement-slow-three",
        title: "慢动作跳跳",
        description: "慢下来，感受身体保持平衡。",
        type: "movement",
        instruction: "慢慢弯膝盖，再轻轻跳起来，一共 3 下。",
        target: 3,
        hint: "一次一次来，不着急，站稳了再跳。",
      }),
      makeLesson("movement", {
        id: "movement-rhythm-four",
        title: "一二一二跳",
        description: "跟着简单口令完成四次小跳。",
        type: "movement",
        instruction: "跟着“一、二、一、二”轻轻跳 4 下。",
        target: 4,
        hint: "双脚一起落地，膝盖软软的会更舒服。",
      }),
    ]),

    life: Object.freeze([
      makeLesson("life", {
        id: "life-wash-hands",
        title: "小手洗干净",
        description: "养成饭前和回家后洗手的习惯。",
        type: "choice",
        instruction: "准备吃水果前，先做什么更卫生？",
        options: [
          { label: "用肥皂洗手", emoji: "🧼", value: "wash" },
          { label: "摸摸鞋底", emoji: "👟", value: "shoe" },
          { label: "把手藏起来", emoji: "🙈", value: "hide" },
        ],
        answer: "wash",
        hint: "让肥皂泡泡照顾小手，每个手指都洗一洗。",
      }),
      makeLesson("life", {
        id: "life-brush-teeth",
        title: "牙齿亮晶晶",
        description: "认识每天早晚刷牙的好习惯。",
        type: "choice",
        instruction: "早上起床后，用什么清洁牙齿？",
        options: [
          { label: "牙刷", emoji: "🪥", value: "toothbrush" },
          { label: "积木", emoji: "🧱", value: "block" },
          { label: "蜡笔", emoji: "🖍️", value: "crayon" },
        ],
        answer: "toothbrush",
        hint: "小牙刷在牙齿上轻轻刷，不用很用力。",
      }),
      makeLesson("life", {
        id: "life-tidy-toys",
        title: "玩具回家啦",
        description: "玩好以后，把玩具送回固定位置。",
        type: "choice",
        instruction: "积木玩好了，接下来怎么做？",
        options: [
          { label: "放回收纳盒", emoji: "🧺", value: "tidy" },
          { label: "留在走道上", emoji: "🚶", value: "floor" },
          { label: "扔到桌子下", emoji: "🪑", value: "under" },
        ],
        answer: "tidy",
        hint: "收好玩具，下一次就能很快找到它。",
      }),
      makeLesson("life", {
        id: "life-ask-before-sharing",
        title: "先问一问",
        description: "练习用友好的话和同伴相处。",
        type: "choice",
        instruction: "想玩小朋友手里的玩具，可以怎么说？",
        options: [
          { label: "我可以一起玩吗？", emoji: "🙂", value: "ask" },
          { label: "直接抢过来", emoji: "✋", value: "grab" },
          { label: "把玩具藏起来", emoji: "🙈", value: "hide" },
        ],
        answer: "ask",
        hint: "先礼貌地问一问，等待对方回答。",
      }),
      makeLesson("life", {
        id: "life-sneeze-elbow",
        title: "哈啾小礼貌",
        description: "学会用手肘遮挡喷嚏。",
        type: "choice",
        instruction: "想打喷嚏时，怎样做更合适？",
        options: [
          { label: "用手肘挡住", emoji: "💪", value: "elbow" },
          { label: "对着别人", emoji: "🗣️", value: "toward" },
          { label: "对着食物", emoji: "🍚", value: "food" },
        ],
        answer: "elbow",
        hint: "把手臂弯起来，用手肘里面轻轻挡住。",
      }),
    ]),
  });

  window.SEVEN_CONTENT = Object.freeze({
    SUBJECT_DEFS,
    DAILY_LESSON_BANK,
  });
})();
